public enum TokenClasseEnum {
    PR, //PALAVRA RESERVADA
    DE, //DELIMITADOR
    OP, //OPERADOR
    CLI, //CONSTANTE LITERAL INTEIRO
    CLR, //CONSTANTE LITERAL REAL (FLOAT, DOUBLE)
    CLL, //CONSTANTE LITERAL LOGICA (TRUE, FALSE)
    ID, //IDENTIFICADOR
    CLS, ////CONSTANTE LITERAL STRING (*)
    EOF
}